### ISSUE TITLE
GitHub actions are broken

### ISSUE THREAD

**Issue by pcagas** [ammarhakim/postgkyl#136]
Postgkyl CI is running into the following problem:

```
Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.12/site-packages/conda/exception_handler.py", line 17, in __call__
    try:
             
  File "/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/main.py", line 83, in main_subshell
  File "/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 199, in do_call
    context.plugin_manager.invoke_pre_commands(command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/lib/python3.12/site-packages/conda/notices/core.py", line 131, in wrapper
  File "/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/main_env_update.py", line 161, in execute
    touch_nonadmin(prefix)
  File "/usr/share/miniconda/lib/python3.12/site-packages/conda/env/env.py", line 278, in print_result
    """Print the result of an install operation"""
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/install.py", line 61, in <module>
    from .main_config import set_keys
ImportError: cannot import name 'set_keys' from 'conda.cli.main_config' (/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/main_config.py)
```

**Comment by pcagas** [comment]
This seems related to https://github.com/conda/conda/issues/13920
