### ISSUE TITLE
problem with `select` near upper boundary and really small coordinates?

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#22]
I have a simulation where the coordinate (mu) goes from 0 to approximately 7e-15.

When I try to select at coordinates > 1.598e-15, I get the following error

```pgkyl gk31-wham1x2v_elc_0.bp interp sel --z2 1.5985e-15 info```
```
Set  (default#0)
Traceback (most recent call last):
  File "/Users/manaure/anaconda3/bin/pgkyl", line 11, in <module>
    sys.exit(cli())
  File "/Users/manaure/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/manaure/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/manaure/anaconda3/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Users/manaure/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/manaure/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/manaure/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/manaure/anaconda3/lib/python3.8/site-packages/postgkyl/commands/info.py", line 34, in info
    click.echo(dat.info() + "\n")
  File "/Users/manaure/anaconda3/lib/python3.8/site-packages/postgkyl/data/data.py", line 592, in info
    maximum = np.nanmax(values)
  File "<__array_function__ internals>", line 5, in nanmax
  File "/Users/manaure/anaconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 434, in nanmax
    res = np.fmax.reduce(a, axis=axis, out=out, **kwargs)
ValueError: zero-size array to reduction operation fmax which has no identity
```

but if I choose I coordinate lower than that, it seems to work. I can provide an example data file, but GitHub doesn't let me attached .bp or .lua.

This is preventing me from being able to examine the distribution function near the boundary :( where some important (but probably undesired) stuff is happening.

**Comment by JunoRavin** [comment]
This is the same error I was getting in Issue #21  so I think there is some subtle bug in how select actually down selects to a floating point value.

**Comment by manauref** [comment]
Also, `interp sel -1 info` seems to give something, presumably the last
cell, but the ranges of that cell are wrong in the info command:

│  └─ Dim 2: Num. cells: 1; Lower: 0.000000e+00; Upper: 1.065599e-16
