### ISSUE TITLE
Potential bug in partial loading, both in command line and script mode.

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#28]
I'm trying to partial load with pgkyl and encountering an error:
pgkyl gk36-wham1x2v_elc_0.bp info
```
Set  (default#0)
├─ Time: 0.000000e+00
├─ Frame: 0
├─ Number of components: 20
├─ Number of dimensions: 3
├─ Grid: (mapped)
│  ├─ Dim 0: Num. cells: 256; Lower: -2.511307e+00; Upper: 2.510300e+00
│  ├─ Dim 1: Num. cells: 48; Lower: -3.045493e+06; Upper: 3.045493e+06
│  └─ Dim 2: Num. cells: 24; Lower: 0.000000e+00; Upper: 1.787552e-16
├─ Maximum: 4.500547e-02 at (0, 20, 0) component 0
├─ Minimum: -2.504019e-03 at (255, 31, 0) component 2
├─ DG info:
│  ├─ Polynomial Order: 2
│  └─ Basis Type: serendipity (modal)
├─ Created with Gkeyll:
│  ├─ Changeset: 4eafb7feccfc+
│  └─ Build Date: Apr  7 2021 21:27:52
```
**pgkyl gk36-wham1x2v_elc_0.bp --z0 129:130 info**
```
Traceback (most recent call last):
  File "/global/homes/m/mana/.conda/envs/pgkylEnv/bin/pgkyl", line 11, in <module>
    sys.exit(cli())
  File "/global/homes/m/mana/.conda/envs/pgkylEnv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/global/homes/m/mana/.conda/envs/pgkylEnv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/global/homes/m/mana/.conda/envs/pgkylEnv/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/global/homes/m/mana/.conda/envs/pgkylEnv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/global/homes/m/mana/.conda/envs/pgkylEnv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/global/homes/m/mana/.conda/envs/pgkylEnv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/global/homes/m/mana/.conda/envs/pgkylEnv/lib/python3.8/site-packages/postgkyl/commands/load.py", line 95, in load
    data.add(Data(fileName=fn, tag=kwargs['tag'],
  File "/global/homes/m/mana/.conda/envs/pgkylEnv/lib/python3.8/site-packages/postgkyl/data/data.py", line 98, in __init__
    self._loadFrame(zs, comp)
  File "/global/homes/m/mana/.conda/envs/pgkylEnv/lib/python3.8/site-packages/postgkyl/data/data.py", line 264, in _loadFrame
    lower[d] = self._grid[0][idx, d]
IndexError: index 129 is out of bounds for axis 0 with size 25
```
Is this a bug?

**Comment by manauref** [comment]
Appears to have been solved in commit 3c93322.
When support for nonuniform grids was fixed earlier this year, we did not carefully look at partial loading.

I'll leave this issue open a little longer in case issues arise.
