### ISSUE TITLE
Potential bug in ev (grad?)

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#30]
Getting the following error when trying to compute the parallel electric field in a 1x2v simulation:

pgkyl "gk36-wham1x2v_phi_[0-9]*.bp" interp ev 'f* 0 grad -1 *' anim --float -x '$z$ (m)' -y '$E_{\parallel}$ (V/m)' --saveas 'gk36-wham1x2v_Epar_41809614.mp4'
```
Traceback (most recent call last):
  File "/global/homes/m/mana/cori/gkeyll/postgkyl/pgkyl", line 6, in <module>
    sys.exit(postgkyl.pgkyl.cli())
  File "/global/homes/m/mana/.conda/envs/pgkylDev/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/global/homes/m/mana/.conda/envs/pgkylDev/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/global/homes/m/mana/.conda/envs/pgkylDev/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/global/homes/m/mana/.conda/envs/pgkylDev/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/global/homes/m/mana/.conda/envs/pgkylDev/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/global/homes/m/mana/.conda/envs/pgkylDev/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/global/u1/m/mana/cori/gkeyll/postgkyl/postgkyl/commands/ev.py", line 228, in ev
    isData = _data(ctx, gridStack, valueStack, metaStack, s, tags, onlyActive)
  File "/global/u1/m/mana/cori/gkeyll/postgkyl/postgkyl/commands/ev.py", line 62, in _data
    if cnt == int(setIdx):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by pcagas** [comment]
Not a bug necessarily. When I did the requested behavior revert, some of the functionality got lost as I mentioned in the message. The indices are mandatory again as they were before, so you need to do 'f[0] 0 grad -1 *'.

I didn't have time yet to redesign it again to have some of the new features and old logic.

**Comment by pcagas** [comment]
I think it is correct in the documentation now.

**Comment by manauref** [comment]
@pcagas I see that there was an error in how the command got formatted when I bold-faced it above. I edited it now.

But your comment may still apply, so I'll try using ```ev 'f[0] 0 grad -1 *'```. So we no longer need to use ```ev 'f*...``` to select all the data loaded?

**Comment by pcagas** [comment]
Oh, I didn't see the wildcard load. In that case, you sadly need to switch to global indexing with `-g` and then you can use the new features like just using `f` or something like this `f[3:7]`. It is unfortunate but it was currently the only way to revert to the logic before the tag update :-(

**Comment by manauref** [comment]
For completeness, here's the command that works now
```pgkyl "gk36-wham1x2v_phi_[0-9]*.bp" interp ev -g 'f[:] 0 grad -1 *' anim```
or in this case the ```[:]``` is not necessary, so the following should work too
```pgkyl "gk36-wham1x2v_phi_[0-9]*.bp" interp ev -g 'f 0 grad -1 *' anim```
