### ISSUE TITLE
Allow scalars produced by ev to be passed to subsequent ev commands (or fix its handling in plot)

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#31]
For example, in trying to plot the density divided by the average density with the following command

```pgkyl sim_elc_M0_0.bp -t m0 interp ev -t m0Av 'm0 0 avg' activate -t m0,m0Av ev 'm0 m0Av /' pl```

I get the following error
```
Traceback (most recent call last):
  File "/Users/manaure/anaconda3/envs/pgkylEnv/bin/pgkyl", line 11, in <module>
    sys.exit(cli())
  File "/Users/manaure/anaconda3/envs/pgkylEnv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/manaure/anaconda3/envs/pgkylEnv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/manaure/anaconda3/envs/pgkylEnv/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Users/manaure/anaconda3/envs/pgkylEnv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/manaure/anaconda3/envs/pgkylEnv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/manaure/anaconda3/envs/pgkylEnv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/manaure/anaconda3/envs/pgkylEnv/lib/python3.8/site-packages/postgkyl/commands/plot.py", line 142, in plot
    gplot(dat, labelPrefix=label,
  File "/Users/manaure/anaconda3/envs/pgkylEnv/lib/python3.8/site-packages/postgkyl/output/plot.py", line 272, in plot
    gridCC = _gridNodalToCellCentered(grid, cells)
  File "/Users/manaure/anaconda3/envs/pgkylEnv/lib/python3.8/site-packages/postgkyl/output/plot.py", line 35, in _gridNodalToCellCentered
    raise ValueError("Something is terribly wrong...")
ValueError: Something is terribly wrong...
```

But perhaps it's something to do with the grid info being messed up because info appears to work but gives the wrong lower/upper
```
pgkyl gf-mirror-1x-p1_elc_M0_0.bp -t m0 interp ev -t m0Av 'm0 0 avg' activate -t m0,m0Av ev 'm0 m0Av /' info
Set ev (ev#0)
├─ Time: 0.000000e+00
├─ Frame: 0
├─ Number of components: 1
├─ Number of dimensions: 1
├─ Grid: (uniform)
│  └─ Dim 0: Num. cells: 128; Lower: 0.000000e+00; Upper: 0.000000e+00
├─ Maximum: 1.710218e+00 at (50,)
├─ Minimum: 2.830108e-01 at (0,)
├─ DG info:
│  ├─ Polynomial Order: 1
│  └─ Basis Type: serendipity (modal)
├─ Created with Gkeyll:
│  ├─ Changeset: c1662f13ea7c+
│  └─ Build Date: Apr 24 2021 12:16:59
```

**Comment by pcagas** [comment]
This is working correctly.
