### ISSUE TITLE
write command not working properly

### ISSUE THREAD

**Issue by tnbernard** [ammarhakim/postgkyl#32]
(1) "pgkyl <file-name> write -m bp" produces the following error: 
Traceback (most recent call last):
  File "/Users/bernard/miniconda3/bin/pgkyl", line 11, in <module>
    sys.exit(cli())
  File "/Users/bernard/miniconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bernard/miniconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/bernard/miniconda3/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bernard/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bernard/miniconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/bernard/miniconda3/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/bernard/miniconda3/lib/python3.7/site-packages/postgkyl/commands/write.py", line 29, in write
    bufferSize=kwargs['buffersize'])
  File "/Users/bernard/miniconda3/lib/python3.7/site-packages/postgkyl/data/data.py", line 682, in write
    if self.time is not None:
AttributeError: 'Data' object has no attribute 'time'
(2) "pgkyl <file-name> write -m txt" does not output the correct x-coordinates for a 1D field. It should be cell-centered values but it produces and x value array with xmin = xLowerBoundary and xmax = xUpperBoundary - dx, when these should actually be xmin = xLowerBoundary + dx/2 and xmax = xUpperBoundary - dx/2.  (See attached text file, for example.)
[neut_M0.txt](https://github.com/ammarhakim/postgkyl/files/6455783/neut_M0.txt)

**Comment by pcagas** [comment]
(2) has been fixed.

I don't think (1) is an issue anymore, at least I can't replicate it. There were some changes to `write` that most likely fixed this. I am closing this for now but @tnbernard if you experience any other problems, please feel free to reopen this and tag me directly.
